name: Maven Build and Docker Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_USERNAME: rgavhale
  DOCKER_PASSWORD: First#1234

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker Image
      run: docker build -t rgavhale/test:latest .
      
    - name: Log in to Docker Hub
      run: docker login -u rgavhale -p First#1234

    - name: Push Docker Image
      run: docker push rgavhale/test:latest
